# Generated by Django 3.2.15 on 2022-09-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('alter_ego', models.CharField(max_length=60)),
                ('universe', models.CharField(max_length=60)),
            ],
        ),
    ]
